version: "3.5"
services:
  identityserver:
    build:
      context: .
      dockerfile: ./src/IdentityServer/AjedrezTomelloso.ServidorIdentidad.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=identityserver.db;Database=identityserver;User=sa;Password=MyP@assw0rd;
    ports:
      - "3883:80"
    depends_on:
      - identityserver.db

  identityserver.db:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment:
      SA_PASSWORD: "MyP@assw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "5225:1433"
    volumes:
      - ${APPDATA}/Data/SQL:/var/opt/mssql/data:rw
